import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createClient} from '@supabase/supabase-js';
import QRCode from 'qrcode';
import {Building2, FileText, UploadCloud, Users, History, ClipboardList, LogOut, QrCode, Download, Eye, ShieldCheck} from 'lucide-react';
import './style.css';

const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = createClient(supabaseUrl, supabaseKey);
const roles = ['admin','engenharia','projetista','encarregado','visualizador'];

function App(){
 const [session,setSession]=useState(null); const [profile,setProfile]=useState(null); const [tab,setTab]=useState('dashboard');
 const [obras,setObras]=useState([]); const [projetos,setProjetos]=useState([]); const [tarefas,setTarefas]=useState([]); const [auditoria,setAuditoria]=useState([]); const [profiles,setProfiles]=useState([]);
 const [loading,setLoading]=useState(true);
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false)}); const {data:{subscription}}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return()=>subscription.unsubscribe()},[]);
 useEffect(()=>{if(session) loadAll()},[session]);
 async function log(acao,entidade='',entidade_id='',detalhe={}){ await supabase.from('auditoria').insert({user_id:session?.user?.id,acao,entidade,entidade_id,detalhe}); }
 async function loadAll(){
  const uid=session.user.id;
  let {data:prof}=await supabase.from('profiles').select('*').eq('id',uid).maybeSingle();
  if(!prof){ await supabase.from('profiles').insert({id:uid,email:session.user.email,role:'visualizador'}); prof={id:uid,email:session.user.email,role:'visualizador'}; }
  setProfile(prof);
  const [{data:o},{data:p},{data:t},{data:a},{data:ps}] = await Promise.all([
    supabase.from('obras').select('*').order('nome'),
    supabase.from('projetos').select('*, obras(nome)').order('created_at',{ascending:false}),
    supabase.from('tarefas').select('*, obras(nome)').order('created_at',{ascending:false}),
    supabase.from('auditoria').select('*').order('created_at',{ascending:false}).limit(100),
    supabase.from('profiles').select('*').order('created_at',{ascending:false})
  ]);
  setObras(o||[]); setProjetos(p||[]); setTarefas(t||[]); setAuditoria(a||[]); setProfiles(ps||[]);
 }
 if(loading) return <div className="center">Carregando...</div>;
 if(!session) return <Login/>;
 const canWrite=['admin','engenharia','projetista'].includes(profile?.role);
 return <div className="app"><aside><h1>ObraCode</h1><small>{profile?.role || 'usuário'}</small><Nav tab={tab} setTab={setTab}/><button className="exit" onClick={()=>supabase.auth.signOut()}><LogOut size={18}/> Sair</button></aside><main><header><div><h2>{title(tab)}</h2><p>Usuário: {session.user.email}</p></div><span className="pill">📱 PWA / celular</span></header>{tab==='dashboard'&&<Dashboard projetos={projetos} tarefas={tarefas}/>} {tab==='obras'&&<Obras obras={obras} reload={loadAll} log={log}/>} {tab==='projetos'&&<Projetos projetos={projetos} reload={loadAll} log={log}/>} {tab==='revisao'&&<NovaRevisao obras={obras} reload={loadAll} log={log} canWrite={canWrite} user={session.user}/>} {tab==='tarefas'&&<Tarefas obras={obras} projetos={projetos} tarefas={tarefas} reload={loadAll} log={log}/>} {tab==='usuarios'&&<Usuarios profiles={profiles} reload={loadAll}/>} {tab==='auditoria'&&<Auditoria auditoria={auditoria}/>}</main></div>
}
function Login(){const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [msg,setMsg]=useState(''); async function signIn(){const {error}=await supabase.auth.signInWithPassword({email,password}); if(error)setMsg(error.message)} async function signUp(){const {error}=await supabase.auth.signUp({email,password}); setMsg(error?error.message:'Conta criada. Verifique o e-mail se o Supabase solicitar confirmação.')} return <div className="login"><div className="box"><h1>ObraCode</h1><p>Gestão profissional de projetos de obra</p><input placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Senha" type="password" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={signIn}>Entrar</button><button className="secondary" onClick={signUp}>Criar conta</button><small>{msg}</small></div></div>}
function Nav({tab,setTab}){const items=[['dashboard',Building2,'Dashboard'],['obras',Building2,'Obras'],['projetos',FileText,'Projetos'],['revisao',UploadCloud,'Nova Revisão'],['tarefas',ClipboardList,'Tarefas'],['usuarios',Users,'Usuários'],['auditoria',History,'Auditoria']];return <nav>{items.map(([k,I,t])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={18}/>{t}</button>)}</nav>}
function title(t){return {dashboard:'Dashboard',obras:'Obras',projetos:'Projetos',revisao:'Nova Revisão',tarefas:'Tarefas',usuarios:'Usuários',auditoria:'Auditoria'}[t]}
function Dashboard({projetos,tarefas}){return <><div className="cards"><Card t="Projetos" v={projetos.length}/><Card t="Vigentes" v={projetos.filter(p=>p.status==='vigente').length}/><Card t="Obsoletos" v={projetos.filter(p=>p.status==='obsoleto').length}/><Card t="Pendências" v={tarefas.filter(t=>t.status!=='concluida').length}/></div><section><h3>Fluxo documental</h3><div className="flow"><span>Upload</span><b>→</b><span>Análise</span><b>→</b><span>Vigente</span><b>→</b><span>QR em campo</span><b>→</b><span>Obsoleto automático</span></div></section></>}
function Card({t,v}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}
function Obras({obras,reload,log}){const [nome,setNome]=useState(''); const [endereco,setEndereco]=useState(''); async function add(){if(!nome)return; const {data,error}=await supabase.from('obras').insert({nome,endereco}).select().single(); if(!error){await log('Criou obra','obras',data.id,{nome}); setNome(''); setEndereco(''); reload()} else alert(error.message)} return <section><h3>Cadastrar obra</h3><div className="grid"><input placeholder="Nome da obra" value={nome} onChange={e=>setNome(e.target.value)}/><input placeholder="Endereço" value={endereco} onChange={e=>setEndereco(e.target.value)}/><button onClick={add}>Cadastrar</button></div><Table heads={['Nome','Endereço','Status']} rows={obras.map(o=>[o.nome,o.endereco,o.status])}/></section>}
function Projetos({projetos,reload,log}){const [q,setQ]=useState(''); const data=projetos.filter(p=>JSON.stringify(p).toLowerCase().includes(q.toLowerCase())); async function status(id,status){await supabase.from('projetos').update({status}).eq('id',id); await log('Alterou status','projetos',id,{status}); reload()} return <section><input placeholder="Buscar projeto, código, disciplina..." value={q} onChange={e=>setQ(e.target.value)}/><div className="tableWrap"><table><thead><tr><th>Código</th><th>Título</th><th>Obra</th><th>Setor</th><th>Disciplina</th><th>Rev.</th><th>Status</th><th>QR</th><th>Ações</th></tr></thead><tbody>{data.map(p=><ProjetoRow key={p.id} p={p} status={status} log={log}/>)}</tbody></table></div></section>}
function ProjetoRow({p,status,log}){const [qr,setQr]=useState(''); useEffect(()=>{QRCode.toDataURL(p.qr_text||p.arquivo_url||p.codigo).then(setQr)},[p.id]); async function baixar(){await log('Baixou arquivo','projetos',p.id,{codigo:p.codigo}); window.open(p.arquivo_url,'_blank')} return <tr><td><b>{p.codigo}</b></td><td>{p.titulo}<br/><small>{p.arquivo_nome}</small></td><td>{p.obras?.nome}</td><td>{p.setor}</td><td>{p.disciplina}</td><td>{p.revisao}</td><td><span className={'status '+p.status}>{p.status}</span></td><td>{p.status==='vigente'?<img className="qr" src={qr}/>:<small>bloqueado</small>}</td><td><button onClick={()=>window.open(p.arquivo_url,'_blank')}><Eye size={15}/></button><button onClick={baixar}><Download size={15}/></button><select value={p.status} onChange={e=>status(p.id,e.target.value)}><option value="vigente">vigente</option><option value="em_analise">em análise</option><option value="obsoleto">obsoleto</option><option value="bloqueado">bloqueado</option></select></td></tr>}
function NovaRevisao({obras,reload,log,canWrite,user}){const [f,setF]=useState({obra_id:'',setor:'',disciplina:'',codigo:'',titulo:'',revisao:'R00',responsavel:''}); const [file,setFile]=useState(null); async function submit(){if(!canWrite)return alert('Seu perfil não tem permissão para cadastrar revisão.'); if(!file||!f.obra_id||!f.codigo||!f.titulo)return alert('Preencha obra, código, título e arquivo.'); await supabase.from('projetos').update({status:'obsoleto'}).eq('codigo',f.codigo).eq('status','vigente'); const path=`${f.obra_id}/${f.codigo}/${f.revisao}-${Date.now()}-${file.name}`; const up=await supabase.storage.from('projetos').upload(path,file,{upsert:true}); if(up.error)return alert(up.error.message); const {data:{publicUrl}}=supabase.storage.from('projetos').getPublicUrl(path); const insert={...f,status:'vigente',arquivo_nome:file.name,arquivo_path:path,arquivo_url:publicUrl,qr_text:publicUrl,created_by:user.id}; const {data,error}=await supabase.from('projetos').insert(insert).select().single(); if(error)return alert(error.message); await log('Cadastrou revisão','projetos',data.id,{codigo:f.codigo,revisao:f.revisao}); alert('Revisão cadastrada. Revisões vigentes anteriores do mesmo código viraram obsoletas.'); setFile(null); reload()} return <section><h3>Cadastrar nova revisão</h3><p>Regra: se já existir projeto vigente com o mesmo código, ele será marcado como obsoleto automaticamente.</p><div className="grid two"><select value={f.obra_id} onChange={e=>setF({...f,obra_id:e.target.value})}><option value="">Selecione a obra</option>{obras.map(o=><option key={o.id} value={o.id}>{o.nome}</option>)}</select>{['setor','disciplina','codigo','titulo','revisao','responsavel'].map(k=><input key={k} placeholder={k} value={f[k]} onChange={e=>setF({...f,[k]:e.target.value})}/>)}</div><label className="upload"><UploadCloud/> Clique para escolher PDF/DWG<input type="file" accept=".pdf,.dwg,.png,.jpg,.jpeg" onChange={e=>setFile(e.target.files[0])}/><b>{file?.name}</b></label><button onClick={submit}><ShieldCheck size={18}/> Cadastrar revisão real</button></section>}
function Tarefas({obras,projetos,tarefas,reload,log}){const [f,setF]=useState({obra_id:'',projeto_id:'',titulo:'',responsavel:'',prazo:'',prioridade:'media'}); async function add(){if(!f.titulo)return; const {data,error}=await supabase.from('tarefas').insert(f).select().single(); if(!error){await log('Criou tarefa','tarefas',data.id,{titulo:f.titulo}); reload()} else alert(error.message)} async function done(id){await supabase.from('tarefas').update({status:'concluida'}).eq('id',id); reload()} return <section><div className="grid"><select onChange={e=>setF({...f,obra_id:e.target.value})}><option>Obra</option>{obras.map(o=><option value={o.id}>{o.nome}</option>)}</select><input placeholder="Tarefa" onChange={e=>setF({...f,titulo:e.target.value})}/><input placeholder="Responsável" onChange={e=>setF({...f,responsavel:e.target.value})}/><input type="date" onChange={e=>setF({...f,prazo:e.target.value})}/><button onClick={add}>Criar tarefa</button></div>{tarefas.map(t=><div className="task" key={t.id}><b>{t.titulo}</b><span>{t.obras?.nome} • {t.responsavel} • {t.prazo}</span><em>{t.status}</em><button onClick={()=>done(t.id)}>Dar baixa</button></div>)}</section>}
function Usuarios({profiles,reload}){async function role(id,role){await supabase.from('profiles').update({role}).eq('id',id); reload()} return <section><h3>Usuários e permissões</h3><div className="tableWrap"><table><thead><tr><th>E-mail</th><th>Nome</th><th>Perfil</th><th>Ativo</th></tr></thead><tbody>{profiles.map(p=><tr><td>{p.email}</td><td>{p.full_name}</td><td><select value={p.role} onChange={e=>role(p.id,e.target.value)}>{roles.map(r=><option>{r}</option>)}</select></td><td>{p.active?'sim':'não'}</td></tr>)}</tbody></table></div><p><b>Permissões:</b> admin tudo; engenharia gerencia; projetista envia revisões; encarregado consulta/tarefas; visualizador consulta projetos.</p></section>}
function Auditoria({auditoria}){return <section><Table heads={['Data','Ação','Entidade','Detalhe']} rows={auditoria.map(a=>[new Date(a.created_at).toLocaleString('pt-BR'),a.acao,a.entidade,JSON.stringify(a.detalhe)])}/></section>}
function Table({heads,rows}){return <div className="tableWrap"><table><thead><tr>{heads.map(h=><th>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{c}</td>)}</tr>)}</tbody></table></div>}

createRoot(document.getElementById('root')).render(<App/>);
